FROM kong:alpine
USER root
RUN apk add --no-cache git
RUN apk add --no-cache luarocks
RUN luarocks install kong-jwt2header
COPY ./config/kong.yml /
RUN cp /etc/kong/kong.conf.default /etc/kong/kong.conf