
apiVersion: apps/v1
kind: Deployment
metadata:
  name: game
  labels:
    app: game
spec:
  replicas: 1
  selector:
    matchLabels:
      app: game
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: game
    spec:
      containers:
      - name: game
        imagePullPolicy: "Always"
        image: registry.digitalocean.com/leari/game-service:latest
        env:
        - name: MONGO_URL
          value: mongodb+srv://game-service:Kxo6yVFTlDj5e8eZ@leari.qoans.mongodb.net/games?retryWrites=true&w=majority
        - name: RABBIT_HOST
          value: 'rabbit-service'
        - name: RABBIT_USER
          value: guest
        - name: RABBIT_PASSWORD
          value: guest
        - name: NEW_RELIC_APP_NAME
          value: game-api
        - name: NEW_RELIC_LICENSE_KEY
          value: 191747ea147dbf51aecbf79cebd5d1d88644NRAL
        ports:
        - containerPort: 3000
--- 
apiVersion: v1
kind: Service
metadata:
  name: game-service
spec:
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: game