
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbit
  labels:
    app: rabbit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbit
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: rabbit
    spec:
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: rabbit
      containers:
      - name: rabbit
        volumeMounts:
          - name: storage
            mountPath: "/var/lib/rabbitmq/mnesia"
        image: rabbitmq:management-alpine
        ports:
          - containerPort: 5672
            protocol: TCP
          - containerPort: 15672
            protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: rabbit-service
spec:
  ports:
    - name: http
      protocol: TCP
      port: 5672
      targetPort: 5672
    - name: http-m
      protocol: TCP
      port: 15672
      targetPort: 15672
  selector:
    app: rabbit

---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: rabbit-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: mrabbit.leari.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: rabbit-service
              servicePort: 15672
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: rabbit
  namespace: default

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi


