version: '3.7'
services:
  api-gateway:
    image: diogo8machado/api-gateway
    environment:
      KONG_PLUGINS: kong-jwt2header,jwt
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: '0.0.0.0:8001'
      KONG_DATABASE: 'off'
      KONG_DECLARATIVE_CONFIG: kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gateway.rule=Host(`api.leari.xyz`)"
      - "traefik.http.routers.gateway.entrypoints=websecure"
      - "traefik.http.routers.gateway.tls.certresolver=myresolver"
      - "traefik.http.services.gateway.loadbalancer.server.port=8000"
    networks:
        - traefik-net
    deploy:
        update_config:
          delay: 60s
          monitor: 30s
          order: stop-first
          failure_action: rollback 
        labels:
        - "traefik.enable=true"
        - "traefik.http.routers.gateway.rule=Host(`api.leari.xyz`)"
        - "traefik.http.routers.gateway.entrypoints=websecure"
        - "traefik.http.routers.gateway.tls.certresolver=myresolver"
        - "traefik.http.services.gateway.loadbalancer.server.port=8000"

networks:
  traefik-net:
    external: true