version: '3.7'
services:
  redis:
    image: redis:alpine
    networks:
        - traefik-new
  eagle-api:
      image: diogo8machado/eagle
      environment: 
        - MONGO_URL=${MONGO_URL}
        - RABBIT_HOST=rabbit
        - RABBIT_USER=${RABBIT_USER}
        - RABBIT_PASSWORD=${RABBIT_PASSWORD}
        - NEW_RELIC_APP_NAME=eagle-api
        - NEW_RELIC_LICENSE_KEY=${NEW_RELIC_LICENSE_KEY}
        - DISCORD_URL=${DISCORD_URL}
        - SONIC_HOST=${SONIC_HOST}
        - SONIC_PASSWORD=${SONIC_PASSWORD}
        - SONIC_PORT=${SONIC_PORT}
        - OPEN_EXCHANGE_TOKEN=${OPEN_EXCHANGE_TOKEN}
        - REDIS_HOST=${REDIS_HOST}
      networks:
        - traefik-new
      command: yarn start:prod:api
      deploy:
        replicas: 1
        update_config:
          parallelism: 1
          order: start-first
          failure_action: rollback
          delay: 10s
        rollback_config:
          parallelism: 0
          order: stop-first
        restart_policy:
          condition: any
          delay: 5s
          max_attempts: 3
          window: 120s
  eagle-job:
      image: diogo8machado/eagle
      environment: 
        - MONGO_URL=${MONGO_URL}
        - RABBIT_HOST=rabbit
        - RABBIT_USER=${RABBIT_USER}
        - RABBIT_PASSWORD=${RABBIT_PASSWORD}
        - NEW_RELIC_APP_NAME=eagle-job
        - NEW_RELIC_LICENSE_KEY=${NEW_RELIC_LICENSE_KEY}
        - DISCORD_URL=${DISCORD_URL}
        - SONIC_HOST=${SONIC_HOST}
        - SONIC_PASSWORD=${SONIC_PASSWORD}
        - SONIC_PORT=${SONIC_PORT}
      networks:
        - traefik-new
      command: yarn start:prod:job
      deploy:
        replicas: 2
        update_config:
          parallelism: 1
          order: start-first
          failure_action: rollback
          delay: 10s
        rollback_config:
          parallelism: 0
          order: stop-first
        restart_policy:
          condition: any
          delay: 5s
          max_attempts: 3
          window: 120s
  rabbit:
      hostname: mabbit
      image: rabbitmq:management-alpine
      volumes:
        - "rabbitmq:/var/lib/rabbitmq/mnesia/"
      labels:
        - "com.datadoghq.ad.check_names=[\"rabbitmq\"]"
        - "com.datadoghq.ad.init_configs=[{}]"
        - "com.datadoghq.ad.instances=[{\"rabbitmq_api_url\":\"%%host%%:15672/api/\",\"username\": \"datadog\", \"password\": \"datadog\"}]"
      networks:
        - traefik-new
      deploy:
        placement:
          constraints: [node.role==manager]
        update_config:
          delay: 60s
          monitor: 30s
          order: stop-first
          failure_action: rollback
        labels:
        - "traefik.enable=true"
        - "traefik.http.routers.rabbit.rule=Host(`mrabbit.leari.xyz`)"
        - "traefik.http.routers.rabbit.service=rabbit"
        - "traefik.http.routers.rabbit.entrypoints=websecure"
        - "traefik.http.routers.rabbit.tls.certresolver=myresolver"
        - "traefik.http.services.rabbit.loadbalancer.server.port=15672"
        - "com.datadoghq.ad.check_names=[\"rabbitmq\"]"
        - "com.datadoghq.ad.init_configs=[{}]"
        - "com.datadoghq.ad.instances=[{\"rabbitmq_api_url\":\"%%host%%:15672/api/\",\"username\": \"datadog\", \"password\": \"datadog\"}]"
volumes:
  rabbitmq:
  postgres:

networks:
  traefik-new:
    external: true