version: '3.7'
services:
  postgres:
    image: postgres:alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    networks:
        - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.postgres.rule=Host(`postgres.leari.xyz`)"
      - "traefik.http.routers.postgres.entrypoints=websecure"
      - "traefik.http.routers.postgres.tls.certresolver=myresolver"
      - "traefik.http.services.postgres.loadbalancer.server.port=5432"
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      PROXY_ADDRESS_FORWARDING: "true"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth.rule=Host(`auth.leari.xyz`)"
      - "traefik.http.routers.auth.entrypoints=websecure"
      - "traefik.http.routers.auth.tls.certresolver=myresolver"
      - "traefik.http.services.auth.loadbalancer.server.port=8080"
    depends_on:
        - postgres
    networks:
        - traefik-net
  eagle:
      image: diogo8machado/eagle
      environment: 
        - MONGO_URL=${MONGO_URL}
        - RABBIT_HOST=rabbit
        - RABBIT_USER=${RABBIT_USER}
        - RABBIT_PASSWORD=${RABBIT_PASSWORD}
        - NEW_RELIC_APP_NAME=eagle
        - NEW_RELIC_LICENSE_KEY=${NEW_RELIC_LICENSE_KEY}
        - DISCORD_URL=${DISCORD_URL}
      networks:
        - traefik-net
  rabbit:
      hostname: mabbit
      image: rabbitmq:management-alpine
      volumes:
        - "rabbitmq:/var/lib/rabbitmq/mnesia/"
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.rabbit.rule=Host(`mrabbit.leari.xyz`)"
        - "traefik.http.routers.rabbit.entrypoints=websecure"
        - "traefik.http.routers.rabbit.tls.certresolver=myresolver"
        - "traefik.http.services.rabbit.loadbalancer.server.port=15672"
        - "com.datadoghq.ad.check_names=[\"rabbitmq\"]"
        - "com.datadoghq.ad.init_configs=[{}]"
        - "com.datadoghq.ad.instances=[{\"rabbitmq_api_url\":\"%%host%%:15672/api/\",\"username\": \"datadog\", \"password\": \"datadog\"}]"
      networks:
        - traefik-net
volumes:
  rabbitmq:
  postgres:

networks:
  traefik-net:
    external: true