version: '3.7'
services:
  game-service:
      image: diogo8machado/game-service
      environment: 
        - MONGO_URL=mongodb+srv://game-service:Kxo6yVFTlDj5e8eZ@leari.qoans.mongodb.net/games?retryWrites=true&w=majority
        - RABBIT_HOST=rabbit
        - RABBIT_USER=guest
        - RABBIT_PASSWORD=guest
        - NEW_RELIC_APP_NAME=game-api
        - NEW_RELIC_LICENSE_KEY=191747ea147dbf51aecbf79cebd5d1d88644NRAL
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.gameapi.rule=Host(`api.leari.xyz`)"
        - "traefik.http.routers.gameapi.entrypoints=websecure"
        - "traefik.http.routers.gameapi.tls.certresolver=myresolver"
        - "traefik.http.services.gameapi.loadbalancer.server.port=3000"
      networks:
        - traefik-net
  rabbit:
      image: rabbitmq:management-alpine
      volumes:
        - "rabbitmq:/var/lib/rabbitmq/mnesia"
      ports:
        - 15672:15672
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.rabbit.rule=Host(`mrabbit.leari.xyz`)"
        - "traefik.http.routers.rabbit.entrypoints=websecure"
        - "traefik.http.routers.rabbit.tls.certresolver=myresolver"
        - "traefik.http.services.rabbit.loadbalancer.server.port=15672"
      networks:
        - traefik-net
volumes:
  rabbitmq:

networks:
  traefik-net:
    external: true