version: '3'
services:
  game-service:
      image: diogo8machado/game-service
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.rabbit.rule=Host(`api.leari.xyz`)"
        - "traefik.http.routers.rabbit.entrypoints=websecure"
        - "traefik.http.routers.rabbit.tls.certresolver=myresolver"
        - "traefik.http.services.myservice.loadbalancer.server.port=3000"
  rabbit:
      image: rabbitmq:management-alpine
      volumes:
        - "rabbitmq:/var/lib/rabbitmq/mnesia"
      ports:
        - 15672:15672
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.rabbit.rule=Host(`mrabbit.leari.xyz`)"
        - "traefik.http.routers.rabbit.entrypoints=websecure"
        - "traefik.http.routers.rabbit.tls.certresolver=myresolver"
        - "traefik.http.services.myservice.loadbalancer.server.port=15672"
volumes:
  rabbitmq: