version: '3.7'
services:
  api-gateway:
    image: diogo8machado/api-gateway
    environment:
      KONG_PLUGINS: kong-jwt2header,jwt
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: '0.0.0.0:8001'
      KONG_DATABASE: 'off'
      KONG_DECLARATIVE_CONFIG: kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gateway.rule=Host(`api.leari.xyz`)"
      - "traefik.http.routers.gateway.entrypoints=websecure"
      - "traefik.http.routers.gateway.tls.certresolver=myresolver"
      - "traefik.http.services.gateway.loadbalancer.server.port=8000"
    networks:
        - traefik-net
  postgres:
    image: postgres:alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    networks:
        - traefik-net
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      PROXY_ADDRESS_FORWARDING: true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth.rule=Host(`auth.leari.xyz`)"
      - "traefik.http.routers.auth.entrypoints=websecure"
      - "traefik.http.routers.auth.tls.certresolver=myresolver"
      - "traefik.http.services.auth.loadbalancer.server.port=8080"
    depends_on:
        - postgres
    networks:
        - traefik-net
  game-crawler:
      image: diogo8machado/game-crawler
      environment: 
        - MONGO_URL=mongodb+srv://game-service:Kxo6yVFTlDj5e8eZ@leari.qoans.mongodb.net/games?retryWrites=true&w=majority
        - RABBIT_HOST=rabbit
        - RABBIT_USER=guest
        - RABBIT_PASSWORD=guest
        - NEW_RELIC_APP_NAME=game-crawler
        - NEW_RELIC_LICENSE_KEY=191747ea147dbf51aecbf79cebd5d1d88644NRAL
        - AWS_ACCESS_KEY_ID=AKIARSYY7UOTLEAPGSRY
        - AWS_SECRET_ACCESS_KEY=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
        - AWS_REGION=us-east-1
        - AWS_S3_BUCKET=leari-prices
        - DISCORD_URL=https://discord.com/api/webhooks/890673551177306192/CBqJSZv_z1W0Y3XZ2z9BhF6_Ut9y7WcKULMAvyTnPdVPeyF_EBncqRT6dMbIrHRkiVYJ
      networks:
        - traefik-net
  game-service:
      image: diogo8machado/game-service
      environment: 
        - MONGO_URL=mongodb+srv://game-service:Kxo6yVFTlDj5e8eZ@leari.qoans.mongodb.net/games?retryWrites=true&w=majority
        - RABBIT_HOST=rabbit
        - RABBIT_USER=guest
        - RABBIT_PASSWORD=guest
        - NEW_RELIC_APP_NAME=game-api
        - NEW_RELIC_LICENSE_KEY=191747ea147dbf51aecbf79cebd5d1d88644NRAL
      networks:
        - traefik-net
  rabbit:
      hostname: mabbit
      image: rabbitmq:management-alpine
      volumes:
        - "rabbitmq:/var/lib/rabbitmq/mnesia/"
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.rabbit.rule=Host(`mrabbit.leari.xyz`)"
        - "traefik.http.routers.rabbit.entrypoints=websecure"
        - "traefik.http.routers.rabbit.tls.certresolver=myresolver"
        - "traefik.http.services.rabbit.loadbalancer.server.port=15672"
        - "com.datadoghq.ad.check_names=[\"rabbitmq\"]"
        - "com.datadoghq.ad.init_configs=[{}]"
        - "com.datadoghq.ad.instances=[{\"rabbitmq_api_url\":\"%%host%%:15672/api/\",\"username\": \"datadog\", \"password\": \"datadog\"}]"
      networks:
        - traefik-net
volumes:
  rabbitmq:
  postgres:

networks:
  traefik-net:
    external: true