version: '3.7'
services:
  eagle-api:
      image: diogo8machado/eagle
      environment: 
        - MONGO_URL=${MONGO_URL}
        - RABBIT_HOST=rabbit
        - RABBIT_USER=${RABBIT_USER}
        - RABBIT_PASSWORD=${RABBIT_PASSWORD}
        - NEW_RELIC_APP_NAME=eagle-api
        - NEW_RELIC_LICENSE_KEY=${NEW_RELIC_LICENSE_KEY}
        - DISCORD_URL=${DISCORD_URL}
      networks:
        - traefik-net
      command: yarn start:prod:api
  eagle-job:
      image: diogo8machado/eagle
      environment: 
        - MONGO_URL=${MONGO_URL}
        - RABBIT_HOST=rabbit
        - RABBIT_USER=${RABBIT_USER}
        - RABBIT_PASSWORD=${RABBIT_PASSWORD}
        - NEW_RELIC_APP_NAME=eagle-job
        - NEW_RELIC_LICENSE_KEY=${NEW_RELIC_LICENSE_KEY}
        - DISCORD_URL=${DISCORD_URL}
      networks:
        - traefik-net
      command: yarn start:prod:job
  rabbit:
      hostname: mabbit
      image: rabbitmq:management-alpine
      volumes:
        - "rabbitmq:/var/lib/rabbitmq/mnesia/"
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.rabbit.rule=Host(`mrabbit.leari.xyz`)"
        - "traefik.http.routers.rabbit.entrypoints=websecure"
        - "traefik.http.routers.rabbit.tls.certresolver=myresolver"
        - "traefik.http.services.rabbit.loadbalancer.server.port=15672"
        - "com.datadoghq.ad.check_names=[\"rabbitmq\"]"
        - "com.datadoghq.ad.init_configs=[{}]"
        - "com.datadoghq.ad.instances=[{\"rabbitmq_api_url\":\"%%host%%:15672/api/\",\"username\": \"datadog\", \"password\": \"datadog\"}]"
      networks:
        - traefik-net
      deploy:
        update_config:
          delay: 60s
          monitor: 30s
          order: stop-first
          failure_action: rollback
        labels:
        - "traefik.enable=true"
        - "traefik.http.routers.rabbit.rule=Host(`mrabbit.leari.xyz`)"
        - "traefik.http.routers.rabbit.entrypoints=websecure"
        - "traefik.http.routers.rabbit.tls.certresolver=myresolver"
        - "traefik.http.services.rabbit.loadbalancer.server.port=15672"
        - "com.datadoghq.ad.check_names=[\"rabbitmq\"]"
        - "com.datadoghq.ad.init_configs=[{}]"
        - "com.datadoghq.ad.instances=[{\"rabbitmq_api_url\":\"%%host%%:15672/api/\",\"username\": \"datadog\", \"password\": \"datadog\"}]"
volumes:
  rabbitmq:
  postgres:

networks:
  traefik-net:
    external: true