version: '3.7'
services:
  postgres-keycloak:
    image: postgres:alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${KEYCLOAK_POSTGRES_DB}
      POSTGRES_USER: ${KEYCLOAK_POSTGRES_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    networks:
        - traefik
  pgbackups3:
    image: diogo8machado/pg-backup
    environment:
      SCHEDULE: '@daily'
      S3_REGION: us-east-1
      S3_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      S3_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      S3_BUCKET: ${KEYCLOAK_BACKUP_S3_BUCKET}
      S3_PREFIX: backup
      POSTGRES_DATABASE: ${KEYCLOAK_POSTGRES_DB}
      POSTGRES_USER: ${KEYCLOAK_POSTGRES_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_POSTGRES_PASSWORD}
      POSTGRES_HOST: postgres-keycloak
      POSTGRES_EXTRA_OPTS: '--schema=public --blobs'
    networks:
      - traefik
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres-keycloak
      DB_DATABASE: ${KEYCLOAK_POSTGRES_DB}
      DB_USER: ${KEYCLOAK_POSTGRES_USER}
      DB_SCHEMA: public
      DB_PASSWORD: ${KEYCLOAK_POSTGRES_PASSWORD}
      PROXY_ADDRESS_FORWARDING: "true"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth.rule=Host(`auth.leari.xyz`)"
      - "traefik.http.routers.auth.entrypoints=websecure"
      - "traefik.http.routers.auth.tls.certresolver=myresolver"
      - "traefik.http.services.auth.loadbalancer.server.port=8080"
    depends_on:
        - postgres
    networks:
        - traefik
volumes:
  postgres:

networks:
  traefik:
    external: true