version: '3.2'

services:
  traefik:
    image: "traefik:latest"
    container_name: "traefik"
    command:
      # - "--log.level=DEBUG"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--api.insecure=true"
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.network=traefik"
      - "--api"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"

      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=diogomachado_8@hotmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "letsencrypt:/letsencrypt"
    networks:
        - traefik
  agent:
    image: portainer/agent:2.9.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    environment:
       AGENT_CLUSTER_ADDR: tasks.agent
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  portainer:
    image: portainer/portainer-ce:2.9.0
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    volumes:
      - portainer_data:/data
    networks:
      - agent_network
      - traefik
    labels:     
      - "traefik.enable=true"     
      - "traefik.http.routers.portainer.rule=Host(`portainer.leari.xyz`)"     
      - "traefik.http.routers.portainer.entrypoints=web"     
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"     
      - "traefik.http.routers.portainer.service=portainer"   
     
      - "traefik.http.routers.edge.rule=Host(`edge.leari.xyz`)"     
      - "traefik.http.routers.edge.entrypoints=web"     
      - "traefik.http.services.edge.loadbalancer.server.port=8000"     
      - "traefik.http.routers.edge.service=edge"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

networks:
  agent_network:
    driver: overlay
  traefik:
    attachable: true
    external: true

volumes:
  portainer_data:
  letsencrypt: