export interface GameUS {
  lastModified: number;
  title: string;
  description: string;
  url: string;
  nsuid: string;
  slug: string;
  boxart: string;
  horizontalHeaderImage: string;
  platform: string;
  releaseDateDisplay: string;
  esrbRating: string;
  numOfPlayers: string;
  featured: boolean;
  freeToStart: boolean;
  esrbDescriptors: string[];
  franchises: string[];
  genres: string[];
  publishers: string[];
  developers: string[];
  generalFilters: string[];
  howToShop: string[];
  playerFilters: string[];
  priceRange: string;
  msrp: number;
  salePrice: number | null;
  lowestPrice: number;
  availability: string[];
  objectID: string;
}
