name: Update-game-stack

on:
  push:
    branches: [main]
    paths: 
      - '.github/workflows/cd-api-gateway.yaml'
      - 'config/api-gateway.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: node:14-alpine
    defaults:
      run:
        working-directory: /ci-cd
    env:
      STACK_NAME: "api-gateway"
      STACK_FILE: "/config/api-gateway.yml"
      PORTAINER_URL: ${{ secrets.PORTAINER_URL }}
      PORTAINER_USER: ${{ secrets.PORTAINER_USER }}
      PORTAINER_PASSWORD: ${{ secrets.PORTAINER_PASSWORD }}
      REPO_USER: ${{ secrets.REPO_USER }}
      REPO_PASSWORD: ${{ secrets.REPO_PASSWORD }}
      SWARM_ID: ${{ secrets.SWARM_ID }}
    steps:
    - name: Install
      run: yarn
    - name: Deploy
      run: node ./main
      

      
          