name: Update-game-stack

on:
  push:
    branches: [main]
    paths: 
      - '.github/workflows/cd-api-gateway.yaml'

jobs:
  update-stack:
    runs-on: ubuntu-latest
    steps:
    - name: Webhook
      uses: distributhor/workflow-webhook@v2
      env:
        webhook_url: "https://portainer.leari.xyz/api/webhooks/03470fbf-a6a7-47dd-aae5-fbbe83ae458d"
        webhook_secret: "Y0uR5ecr3t"

      
          