name: CD-eagle-build

on:
  push:
    branches: [main]
    paths: 
      - 'eagle/**'
      - '.github/workflows/cd-eagle-build.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./eagle
    steps:
      - uses: actions/checkout@v2
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: diogo8machado/eagle
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          workdir: ./eagle
  deploy:
      needs: build
      runs-on: ubuntu-latest
      steps:
      - name: Webhook
        uses: distributhor/workflow-webhook@v2
        env:
          webhook_url: "https://portainer.leari.xyz/api/webhooks/03470fbf-a6a7-47dd-aae5-fbbe83ae458d"
          webhook_secret: "Y0uR5ecr3t"