name: CD-game-service

on:
  push:
    branches: [main]
    paths: 
      - 'game-service/**'
      - '!game-service/config/deployment.yml'
      - '.github/workflows/cd-game-service-build.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./game-service
    steps:
      - uses: actions/checkout@v2
      - name: test
        run: ls
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: diogo8machado/game-service
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}