name: CD-game-service

on:
  push:
    branches: [main]
    paths: 
      - '.github/workflows/cd-game-service.yaml'
      - 'config/game.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Webhook
      uses: distributhor/workflow-webhook@v2
      with:
        url: "https://167.71.31.79:9443/api/stacks/webhooks/1b74ef9b-7ebf-44ec-a347-765f4fe1e2f0"

      
          