name: CD-game-service

on:
  push:
    branches: [main]
    paths: 
      - 'services/rabbit.yml'
      - '.github/workflows/cd-rabbit.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./services
    steps:
      - uses: actions/checkout@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      
      - name: Save DigitalOcean kubeconfig with short-lived credentials
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 k8s-leari

      - name: Deploy to DigitalOcean Kubernetes
        run: kubectl apply -f $GITHUB_WORKSPACE/services/rabbit.yml

      - name: Verify deployment
        run: kubectl rollout status deployment/rabbit